version: "3.5"
services:
    nginx:
        image: nginx:alpine
        container_name: dacxi-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        depends_on:
            - php
        networks:
            - dacxi
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - dacxi
    mysql:
        image: mysql:latest
        restart: unless-stopped
        tty: true
        environment:
            - TZ=UTC
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        ports:
            - "3306:3306"
        networks:
            - dacxi
networks:
    dacxi:
        driver: bridge
