<?php

namespace App\Constants;

class AssetConstants {
    const ETHEREUM = 'ethereum';
    const TERRA = 'terra';
    const BITCOIN = 'bitcoin';
    const DACXI = 'dacxi';
    const COSMOS = 'cosmos hub';
    const DOGECOIN = 'dogecoin';
    const TETHER = 'tether';

    const ASSETS_SYMBOLS = [
        self::ETHEREUM => 'eth',
        self::TERRA => 'luna',
        self::BITCOIN => 'btc',
        self::DACXI => 'dacxi',
        self::COSMOS => 'atom',
        self::TETHER => 'usdt'
    ];

    // const ASSETS_SLUG = [
    //     self::ETHEREUM => 'ethereum',
    //     self::TERRA => 'terra',
    //     self::BITCOIN => 'bitcoin',
    //     self::DACXI => 'dacxi',
    //     self::COSMOS => 'cosmos hub',
    //     self::TETHER => 'tether'
    // ];

    const ASSETS_SLUG = [
        "aave",
        "algorand",
        "apecoin",
        "aptos",
        "arweave",
        "bitcoin",
        "bitdao",
        "bittorrent",
        "cardano",
        "cdai",
        "chainlink",
        "chiliz",
        "dai",
        "dash",
        "decentraland",
        "dogecoin",
        "ecash",
        "eos",
        "ethereum",
        "evmos",
        "fantom",
        "filecoin",
        "flow",
        "frax",
        "helium",
        "iota",
        "kava",
        "litecoin",
        "maker",
        "monero",
        "neo",
        "nexo",
        "okb",
        "osmosis",
        "polkadot",
        "radix",
        "solana",
        "stellar",
        "tether",
        "tezos",
        "thorchain",
        "tron",
        "uniswap",
        "usdd",
        "vechain",
        "zcash",
        "zilliqa",
        "XDC Network",
        "Casper Network",
        "Tether Gold",
        "Rocket Pool",
        "Celsius Network",
        "ECOMI",
        "Decred",
        "cUSDT",
        "DeFiChain",
        "Terra",
        "Amp",
        "Maiar DEX",
        "1inch",
        "Convex Finance",
        "Ravencoin",
        "Holo",
        "Theta Fuel",
        "NEM",
        "TerraClassicUSD",
        "ImmutableX",
        "Nexus Mutual",
        "Celo",
        "Loopring",
        "Compound",
        "Waves",
        "GMX",
        "Sushi",
        "Oasis Network",
        "Bitcoin Gold",
        "STEPN",
        "Kusama",
        "Gnosis",
        "Gala",
        "Qtum",
        "OKC",
        "Olympus",
        "IoTeX",
        "Serum",
        "SafeMoon [OLD]",
        "Golem",
        "Livepeer",
        "Reserve Rights",
        "IOST",
        "Huobi BTC",
        "Kadena",
        "yearn.finance",
        "Dogelon Mars",
        "JUST",
        "Balancer",
        "Convex CRV",
        "Harmony",
        "Bone ShibaSwap",
        "Ankr",
        "Polymath",
        "Rocket Pool ETH",
        "Mask Network",
        "Marinade staked SOL",
        "Optimism",
        "OMG Network",
        "Escoin",
        "Render",
        "LINK",
        "0x",
        "SwissBorg",
        "Injective",
        "dYdX",
        "Tenset",
        "WOO Network",
        "Moonbeam",
        "Merit Circle",
        "Baby Doge Coin",
        "Audius",
        "Euro Tether",
        "Flux",
        "ICON",
        "Ontology",
        "Magic Internet Money",
        "Bitgert",
        "Liquity USD",
        "Ribbon Finance",
        "WAX",
        "Synapse",
        "NuCypher",
        "VVS Finance",
        "JUNO",
        "SafeMoon",
        "Aleph Zero",
        "Hive",
        "Coinmetro",
        "Energy Web",
        "APENFT",
        "Alchemix USD",
        "Chia",
        "Horizen",
        "Constellation",
        "Siacoin",
        "Secret",
        "SXP",
        "Astar",
        "DAO Maker"
    ];
}