<?php

namespace App\Constants;

class AssetConstants {
    const ETHEREUM = 'ethereum';
    const TERRA = 'terra';
    const BITCOIN = 'bitcoin';
    const DACXI = 'dacxi';
    const COSMOS = 'cosmos hub';
    const DOGECOIN = 'dogecoin';
    const TETHER = 'tether';

    const ASSETS_SYMBOLS = [
        self::ETHEREUM => 'eth',
        self::TERRA => 'luna',
        self::BITCOIN => 'btc',
        self::DACXI => 'dacxi',
        self::COSMOS => 'atom',
        self::TETHER => 'usdt'
    ];

    const ASSETS_SLUG = [
        self::ETHEREUM => 'ethereum',
        self::TERRA => 'terra',
        self::BITCOIN => 'bitcoin',
        self::DACXI => 'dacxi',
        self::COSMOS => 'cosmos hub',
        self::TETHER => 'tether'
    ];

    const ASSETS_IDS = [
        "bitcoin",
        "ethereum",
        "tether",
        "binancecoin",
        "usd-coin",
        "ripple",
        "binance-usd",
        "dogecoin",
        "cardano",
        "solana",
        "matic-network",
        "polkadot",
        "shiba-inu",
        "staked-ether",
        "tron",
        "dai",
        "avalanche-2",
        "uniswap",
        "wrapped-bitcoin",
        "leo-token",
        "okb",
        "cosmos",
        "litecoin",
        "chainlink",
        "ftx-token",
        "ethereum-classic",
        "stellar",
        "crypto-com-chain",
        "monero",
        "algorand",
        "near",
        "quant-network",
        "bitcoin-cash",
        "vechain",
        "flow",
        "filecoin",
        "terra-luna",
        "hedera-hashgraph",
        "apecoin",
        "elrond-erd-2",
        "internet-computer",
        "chain-2",
        "tokenize-xchange",
        "the-sandbox",
        "tezos",
        "chiliz",
        "frax",
        "whitebit",
        "aave",
        "decentraland",
        "theta-token",
        "eos",
        "huobi-token",
        "lido-dao",
        "aptos",
        "axie-infinity",
        "kucoin-shares",
        "bitcoin-cash-sv",
        "paxos-standard",
        "true-usd",
        "maker",
        "compound-usd-coin",
        "bittorrent",
        "klay-token",
        "osmosis",
        "ecash",
        "usdd",
        "iota",
        "evmos",
        "gatechain-token",
        "ethereum-pow-iou",
        "pancakeswap-token",
        "zcash",
        "havven",
        "the-graph",
        "fantom",
        "btse-token",
        "compound-ether",
        "neo",
        "radix",
        "nexo",
        "gemini-dollar",
        "cdai",
        "helium",
        "arweave",
        "trust-wallet-token",
        "curve-dao-token",
        "mina-protocol",
        "pax-gold",
        "thorchain",
        "bitdao",
        "zilliqa",
        "dash",
        "rocket-pool",
        "enjincoin",
        "frax-share",
        "basic-attention-token",
        "kava",
        "blockstack",
        "xdce-crowd-sale"
    ];
}